version: '3'
services:
  client:
    image: recipe-client:0.0.1
    ports:
      - "4173:80"
    restart: unless-stopped

  server:
    image: recipe-server:0.0.1
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    environment:
      #        - MONGO_INITDB_ROOT_USERNAME=user
      #        - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mevn
    restart: unless-stopped
volumes:
  dbdata6: